# Generated by Django 4.2 on 2023-04-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_libne_2',
            new_name='address_line_2',
        ),
    ]
